--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.338.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 5/26/2023 5:37:09 PM
-- Server version: 8.0.26
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE sql12613779;

--
-- Drop procedure `proc_certificate_BanMultiple`
--
DROP PROCEDURE IF EXISTS proc_certificate_BanMultiple;

--
-- Drop procedure `proc_certificate_DeleteMultiple`
--
DROP PROCEDURE IF EXISTS proc_certificate_DeleteMultiple;

--
-- Drop procedure `Proc_Certificate_SendMultiple`
--
DROP PROCEDURE IF EXISTS Proc_Certificate_SendMultiple;

--
-- Drop procedure `Proc_Certificate_SignMultiple`
--
DROP PROCEDURE IF EXISTS Proc_Certificate_SignMultiple;

--
-- Drop procedure `proc_user_delete`
--
DROP PROCEDURE IF EXISTS proc_user_delete;

--
-- Drop procedure `proc_user_insert`
--
DROP PROCEDURE IF EXISTS proc_user_insert;

--
-- Drop procedure `proc_certificate_ban`
--
DROP PROCEDURE IF EXISTS proc_certificate_ban;

--
-- Drop procedure `proc_certificate_delete`
--
DROP PROCEDURE IF EXISTS proc_certificate_delete;

--
-- Drop procedure `proc_certificate_getAllIssued`
--
DROP PROCEDURE IF EXISTS proc_certificate_getAllIssued;

--
-- Drop procedure `proc_certificate_getAllReceived`
--
DROP PROCEDURE IF EXISTS proc_certificate_getAllReceived;

--
-- Drop procedure `proc_certificate_insert`
--
DROP PROCEDURE IF EXISTS proc_certificate_insert;

--
-- Drop procedure `proc_certificate_send`
--
DROP PROCEDURE IF EXISTS proc_certificate_send;

--
-- Drop procedure `proc_certificate_sign`
--
DROP PROCEDURE IF EXISTS proc_certificate_sign;

--
-- Drop procedure `proc_Certificate_UpdateAfterSent`
--
DROP PROCEDURE IF EXISTS proc_Certificate_UpdateAfterSent;

--
-- Drop procedure `proc_dashboard_getInfor`
--
DROP PROCEDURE IF EXISTS proc_dashboard_getInfor;

--
-- Drop table `certificate`
--
DROP TABLE IF EXISTS certificate;

--
-- Drop procedure `proc_contact_accept`
--
DROP PROCEDURE IF EXISTS proc_contact_accept;

--
-- Drop procedure `proc_contact_delete`
--
DROP PROCEDURE IF EXISTS proc_contact_delete;

--
-- Drop procedure `proc_contact_getAll`
--
DROP PROCEDURE IF EXISTS proc_contact_getAll;

--
-- Drop procedure `proc_contact_insert`
--
DROP PROCEDURE IF EXISTS proc_contact_insert;

--
-- Drop table `contact`
--
DROP TABLE IF EXISTS contact;

--
-- Drop table `user`
--
DROP TABLE IF EXISTS user;

--
-- Set default database
--
USE sql12613779;

--
-- Create table `user`
--
CREATE TABLE user (
  UserID varchar(255) NOT NULL DEFAULT '' COMMENT 'Khóa chính, là địa chỉ ví skate',
  UserCode mediumint UNSIGNED NOT NULL COMMENT 'Mã code, để hiển thị lên trang web',
  UserName varchar(255) DEFAULT NULL COMMENT 'Tên tổ chức',
  Logo text DEFAULT NULL,
  CreatedDate datetime DEFAULT NULL COMMENT 'Ngày tạo tài khoản',
  IsVerified tinyint DEFAULT 0 COMMENT 'Đã được xác thực hay chưa (0-chưa; 1- rồi)',
  IsDeleted tinyint DEFAULT 0 COMMENT 'Bị xóa hay chưa (0-chưa xóa; 1-đã xóa)',
  PRIMARY KEY (UserID)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 963,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create index `UserCode` on table `user`
--
ALTER TABLE user
ADD UNIQUE INDEX UserCode (UserCode);

--
-- Create table `contact`
--
CREATE TABLE contact (
  ContactID char(36) NOT NULL DEFAULT '' COMMENT 'Khóa chính, có kiểu GUID',
  IssuedID varchar(255) NOT NULL DEFAULT '' COMMENT 'Khóa ngoại, liên kết với bảng user(PolicyID)',
  ReceivedID varchar(255) NOT NULL DEFAULT '' COMMENT 'Khóa ngoại, liên kết với bảng user(PolicyID)',
  ContactCode mediumint UNSIGNED NOT NULL COMMENT 'mã hiện thị trên website, có kiểu là số',
  ContactStatus tinyint DEFAULT 1 COMMENT 'Trạng thái kết nối (1-pending, 2-connected)',
  CreatedDate datetime DEFAULT NULL COMMENT 'Ngày tạo',
  IsDeleted tinyint NOT NULL COMMENT 'xóa hay chưa (0-hiện/1-ẩn)',
  PRIMARY KEY (ContactID)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 1092,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create index `ContactCode` on table `contact`
--
ALTER TABLE contact
ADD UNIQUE INDEX ContactCode (ContactCode);

--
-- Create foreign key
--
ALTER TABLE contact
ADD CONSTRAINT FK_contact_IssuedID FOREIGN KEY (IssuedID)
REFERENCES user (UserID);

--
-- Create foreign key
--
ALTER TABLE contact
ADD CONSTRAINT FK_contact_ReceivedID FOREIGN KEY (ReceivedID)
REFERENCES user (UserID);

DELIMITER $$

--
-- Create procedure `proc_contact_insert`
--
CREATE DEFINER = 'admin'@'%'
PROCEDURE proc_contact_insert (IN v_IssuedID varchar(255), IN v_ReceivedID varchar(255))
COMMENT 'Thêm mới một liên lạc'
BEGIN
  -- Lấy giá trị lớn nhất của user code
  DECLARE CODE mediumint;
  SELECT
    MAX(ContactCode) INTO CODE
  FROM contact;

  -- Check if the contact already exists
  IF (SELECT
        COUNT(*)
      FROM contact c
      WHERE c.IssuedID = v_IssuedID
      AND c.ReceivedID = v_ReceivedID) > 0 THEN
    -- Contact already exists, do nothing
    SELECT
      '';
  ELSE
    -- Nếu table xxx chưa có data sẽ mặc định CODE = 100000
    IF CODE IS NULL THEN
      SET CODE = 100000;
    ELSE
      SET CODE = CODE + 1;
    END IF;

    -- Thực hiện insert
    INSERT INTO contact
      VALUES (UUID(), v_IssuedID, v_ReceivedID, CODE, 1,  -- ContactStatus (Pending)
      NOW(), 0);
  END IF;
END
$$

--
-- Create procedure `proc_contact_getAll`
--
CREATE DEFINER = 'admin'@'%'
PROCEDURE proc_contact_getAll (IN v_UserID varchar(255))
COMMENT 'Lấy tất cả liên hệ của 1 user bằng địa chỉ ví stake'
BEGIN
  SELECT
    c.ContactID,
    c.ContactCode,
    c.IssuedID,
    c.ReceivedID,
    u.UserName AS `ContactName`,
    c.CreatedDate,
    c.ContactStatus
  FROM user u
    JOIN contact c
      ON u.UserID = c.ReceivedID
      OR u.UserID = c.IssuedID

  -- Check conditions
  WHERE c.IsDeleted = 0
  AND ((c.ReceivedID = v_UserID
  AND c.IssuedID = u.UserID)
  OR (c.IssuedID = v_UserID
  AND c.ReceivedID = u.UserID))


  ORDER BY c.CreatedDate ASC;
END
$$

--
-- Create procedure `proc_contact_delete`
--
CREATE DEFINER = 'admin'@'%'
PROCEDURE proc_contact_delete (IN v_ContactID char(36))
COMMENT 'Ẩn 1 liên hệ'
BEGIN
  UPDATE contact c
  SET c.IsDeleted = 1
  WHERE c.ContactID = v_ContactID;
END
$$

--
-- Create procedure `proc_contact_accept`
--
CREATE DEFINER = 'admin'@'%'
PROCEDURE proc_contact_accept (IN v_ContactID char(36))
BEGIN
  UPDATE contact c
  SET c.ContactStatus = 2
  WHERE c.ContactID = v_ContactID;
END
$$

DELIMITER ;

--
-- Create table `certificate`
--
CREATE TABLE certificate (
  CertificateID char(36) NOT NULL DEFAULT '' COMMENT 'Khóa ngoại, liên kết với bảng user(PolicyID)',
  IssuedID varchar(255) NOT NULL DEFAULT '' COMMENT 'Khóa ngoại, liên kết với bảng user(PolicyID)',
  ReceivedID varchar(255) NOT NULL DEFAULT '' COMMENT 'Khóa ngoại, liên kết với bảng user(PolicyID)',
  CertificateCode mediumint NOT NULL COMMENT 'Mã code, để hiển thị lên trang web',
  CertificateType varchar(255) NOT NULL COMMENT 'Kiểu bằng cấp (0-Education Certificate)',
  CertificateName varchar(255) NOT NULL DEFAULT '' COMMENT 'Tên bằng cấp (Bằng kỹ sư, bằng cử nhân)',
  ReceivedAddressWallet varchar(255) DEFAULT NULL COMMENT 'Địa chỉ ví người nhận',
  ReceivedIdentityNumber varchar(255) DEFAULT '' COMMENT 'số CCCD/CMND của người nhận',
  ReceivedName varchar(255) DEFAULT NULL COMMENT 'Tên người nhận bằng',
  ReceivedDoB date DEFAULT NULL COMMENT 'Ngày sinh người nhận bằng',
  YearOfGraduation smallint DEFAULT NULL,
  Classification varchar(50) NOT NULL DEFAULT '' COMMENT 'Loại bằng cấp',
  ModeOfStudy varchar(255) DEFAULT NULL COMMENT 'Hình thức đào tạo (0-Chính quy tập trung, 1-Tại chức)',
  IpfsLink varchar(255) DEFAULT NULL COMMENT 'Mã ipfs của ảnh bằng',
  ImageLink text DEFAULT NULL COMMENT 'Đường link ảnh trên cloudbinary',
  TransactionLink varchar(255) DEFAULT NULL COMMENT 'Mã hash của giao dịch cấp bằng',
  AssetID varchar(255) DEFAULT NULL,
  CertificateStatus tinyint DEFAULT 1 COMMENT 'Trạng thái của bằng cấp (1-Draft/2-Signed/3-Sent/4-Banned)',
  CreatedDate datetime DEFAULT NULL,
  SignedDate datetime DEFAULT NULL COMMENT 'Ngày kí',
  SentDate datetime DEFAULT NULL COMMENT 'Ngày tháng xuất/nhận bằng',
  IsDeleted tinyint DEFAULT NULL,
  PRIMARY KEY (CertificateID)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 1092,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create index `CertificateCode` on table `certificate`
--
ALTER TABLE certificate
ADD UNIQUE INDEX CertificateCode (CertificateCode);

--
-- Create foreign key
--
ALTER TABLE certificate
ADD CONSTRAINT FK_certificate_IssuedID FOREIGN KEY (IssuedID)
REFERENCES user (UserID);

--
-- Create foreign key
--
ALTER TABLE certificate
ADD CONSTRAINT FK_certificate_ReceivedID FOREIGN KEY (ReceivedID)
REFERENCES user (UserID);

DELIMITER $$

--
-- Create procedure `proc_dashboard_getInfor`
--
CREATE DEFINER = 'admin'@'%'
PROCEDURE proc_dashboard_getInfor (IN v_UserID varchar(255),
OUT v_Username varchar(255),
OUT v_IsVerified tinyint,
OUT v_Logo varchar(255),
OUT v_Pending int,
OUT v_Connected int,
OUT v_Draft int,
OUT v_Signed int,
OUT v_Sent int,
OUT v_Banned int,
OUT v_Received int)
COMMENT 'Lấy tất cả liên hệ của 1 user bằng địa chỉ ví stake'
BEGIN
  SELECT
    UserName INTO v_Username
  FROM user
  WHERE UserID = v_UserID;

  SELECT
    isVerified INTO v_IsVerified
  FROM user
  WHERE UserID = v_UserID;

  SELECT
    Logo INTO v_Logo
  FROM user
  WHERE UserID = v_UserID;

  SELECT
    IFNULL(COUNT(c.ContactID), 0) INTO v_Pending
  FROM contact c
  WHERE (c.IssuedID = v_UserID
  OR c.ReceivedID = v_UserID)
  AND c.ContactStatus = 1
  AND c.IsDeleted = 0;

  SELECT
    IFNULL(COUNT(c.ContactID), 0) INTO v_Connected
  FROM contact c
  WHERE (c.IssuedID = v_UserID
  OR c.ReceivedID = v_UserID)
  AND c.ContactStatus = 2
  AND c.IsDeleted = 0;

  SELECT
    IFNULL(COUNT(c.IssuedID), 0) INTO v_Draft
  FROM certificate c
  WHERE (c.IssuedID = v_UserID)
  AND c.CertificateStatus = 1
  AND c.IsDeleted = 0;

  SELECT
    IFNULL(COUNT(c.IssuedID), 0) INTO v_Signed
  FROM certificate c
  WHERE c.IssuedID = v_UserID
  AND c.CertificateStatus = 2
  AND c.IsDeleted = 0;

  SELECT
    IFNULL(COUNT(c.IssuedID), 0) INTO v_Sent
  FROM certificate c
  WHERE c.IssuedID = v_UserID
  AND c.CertificateStatus = 3
  AND c.IsDeleted = 0;

  SELECT
    IFNULL(COUNT(c.IssuedID), 0) INTO v_Banned
  FROM certificate c
  WHERE c.IssuedID = v_UserID
  AND c.CertificateStatus = 4
  AND c.IsDeleted = 0;

  SELECT
    IFNULL(COUNT(c.ReceivedID), 0) INTO v_Received
  FROM certificate c
  WHERE c.ReceivedID = v_UserID
  AND c.CertificateStatus = 3
  AND c.IsDeleted = 0;
END
$$

--
-- Create procedure `proc_Certificate_UpdateAfterSent`
--
CREATE DEFINER = 'admin'@'%'
PROCEDURE proc_Certificate_UpdateAfterSent (IN v_CertificateID varchar(255), IN v_TransactionLink varchar(255), IN v_AssetID varchar(255))
BEGIN
  UPDATE certificate
  SET TransactionLink = v_TransactionLink,
      AssetID = v_AssetID
  WHERE CertificateID = v_CertificateID;
END
$$

--
-- Create procedure `proc_certificate_sign`
--
CREATE DEFINER = 'admin'@'%'
PROCEDURE proc_certificate_sign (IN v_CertificateID char(36))
COMMENT 'Kí 1 bằng theo CertificateID'
BEGIN
  UPDATE certificate c
  SET c.CertificateStatus = 2,
      c.SignedDate = NOW()
  WHERE c.CertificateID = v_CertificateID;
END
$$

--
-- Create procedure `proc_certificate_send`
--
CREATE DEFINER = 'admin'@'%'
PROCEDURE proc_certificate_send (IN v_CertificateID char(36))
COMMENT 'Gửi 1 bằng theo CertificateID'
BEGIN
  UPDATE certificate c
  SET c.CertificateStatus = 3,
      c.SentDate = NOW()
  WHERE c.CertificateID = v_CertificateID;
END
$$

--
-- Create procedure `proc_certificate_insert`
--
CREATE DEFINER = 'admin'@'%'
PROCEDURE proc_certificate_insert (IN v_IssuedID varchar(255),
IN v_ReceivedID varchar(255),
IN v_ReceivedAddressWallet varchar(255),
IN v_ReceivedIdentityNumber varchar(255),
IN v_CertificateName varchar(255),
IN v_ReceivedName varchar(255),
IN v_ReceivedDoB date,
IN v_YearOfGraduation smallint,
IN v_Classification varchar(50),
IN v_ModeOfStudy varchar(255))
BEGIN
  -- Lấy giá trị lớn nhất của user code
  DECLARE CODE mediumint;
  SELECT
    MAX(certificatecode) INTO CODE
  FROM certificate;

  -- Nếu table xxx chưa có data sẽ mặc định CODE = 100000
  IF CODE IS NULL THEN
    SET CODE = 100000;
  ELSE
    SET CODE = CODE + 1;
  END IF;

  INSERT INTO certificate
    VALUES (UUID(), v_IssuedID, v_ReceivedID, CODE, 'UTC', v_CertificateName, v_ReceivedAddressWallet, v_ReceivedIdentityNumber, v_ReceivedName, v_ReceivedDoB, v_YearOfGraduation, v_Classification, v_ModeOfStudy, '', -- ipfslink
    '', -- imagelink
    '', -- transactionlink
    1, -- CertificateStatus: Draft
    NOW(), -- CreatedDate: NOW
    NULL, -- SignedDate: NULL
    NULL, -- SentDate: NULL
    0); -- IsDeleted: Chua xoa

  -- Them contact voi nguoi gui bang
  CALL proc_contact_insert(v_IssuedID, v_ReceivedID);
END
$$

--
-- Create procedure `proc_certificate_getAllReceived`
--
CREATE DEFINER = 'admin'@'%'
PROCEDURE proc_certificate_getAllReceived (IN v_ReceivedID varchar(255))
BEGIN
  SELECT
    c.CertificateID,
    c.ImageLink,
    c.TransactionLink,
    c.CertificateCode,
    u.UserName AS `OganizationName`,
    u.IsVerified,
    c.ReceivedIdentityNumber,
    c.ReceivedName,
    c.ReceivedDoB,
    c.CertificateName,
    c.YearOfGraduation,
    c.Classification,
    c.ModeOfStudy,
    c.SentDate AS `ReceivedDate`
  FROM certificate c
    JOIN user u
      ON c.IssuedID = u.UserID
  -- Check conditions
  WHERE c.ReceivedID = v_ReceivedID
  AND c.CertificateStatus = 3
  AND c.IsDeleted = 0

  ORDER BY c.CreatedDate;
END
$$

--
-- Create procedure `proc_certificate_getAllIssued`
--
CREATE DEFINER = 'admin'@'%'
PROCEDURE proc_certificate_getAllIssued (IN v_IssuerID varchar(255))
BEGIN
  SELECT
    c.CertificateID,
    c.ImageLink,
    c.TransactionLink,
    (SELECT
        UserName
      FROM user
      WHERE UserID = v_IssuerID) AS OrganizationName,
    c.ReceivedIdentityNumber,
    c.ReceivedDoB,
    c.YearOfGraduation,
    c.Classification,
    c.ModeOfStudy,
    c.IpfsLink,
    c.SentDate,
    c.ReceivedAddressWallet,
    c.CertificateCode,
    c.CertificateType,
    c.CertificateName,
    c.ReceivedName,
    c.SignedDate,
    c1.ContactStatus,
    c.CertificateStatus

  FROM certificate c
    JOIN user u
      ON c.ReceivedID = u.UserID
    JOIN contact c1
      ON u.UserID = c1.ReceivedID
  WHERE c.IssuedID = v_IssuerID
  AND c1.IssuedID = v_IssuerID
  AND c.IsDeleted = 0
  ORDER BY c.CreatedDate DESC;
END
$$

--
-- Create procedure `proc_certificate_delete`
--
CREATE DEFINER = 'admin'@'%'
PROCEDURE proc_certificate_delete (IN v_CertificateID char(36))
BEGIN
  UPDATE certificate c
  SET c.IsDeleted = 1
  WHERE c.CertificateID = v_CertificateID;
END
$$

--
-- Create procedure `proc_certificate_ban`
--
CREATE DEFINER = 'admin'@'%'
PROCEDURE proc_certificate_ban (IN v_CertificateID char(36))
BEGIN
  UPDATE certificate c
  SET c.CertificateStatus = 4
  WHERE c.CertificateID = v_CertificateID;
END
$$

--
-- Create procedure `proc_user_insert`
--
CREATE DEFINER = 'admin'@'%'
PROCEDURE proc_user_insert (IN v_UserID varchar(255), IN v_UserName varchar(255), IN v_Logo varchar(255))
COMMENT 'Procedure thêm mới 1 nguoi dung'
BEGIN
  -- Lấy giá trị lớn nhất của user code
  DECLARE CODE mediumint;
  SELECT
    MAX(UserCode) INTO CODE
  FROM user;

  -- Nếu table xxx chưa có data sẽ mặc định CODE = 100000
  IF CODE IS NULL THEN
    SET CODE = 100000;
  ELSE
    SET CODE = CODE + 1;
  END IF;

  INSERT INTO user
    VALUES (v_UserID, CODE, v_UserName, v_Logo, NOW(), 0, 0);
END
$$

--
-- Create procedure `proc_user_delete`
--
CREATE DEFINER = 'admin'@'%'
PROCEDURE proc_user_delete (IN v_UserID varchar(255))
COMMENT 'Xóa 1 người dùng'
BEGIN
  UPDATE user u
  SET u.IsDeleted = 1
  WHERE u.UserID = v_UserID;
END
$$

--
-- Create procedure `Proc_Certificate_SignMultiple`
--
CREATE DEFINER = 'admin'@'%'
PROCEDURE Proc_Certificate_SignMultiple (IN v_CertificateIDs text)
BEGIN
  SET @v_CertificateIDs = REPLACE(v_CertificateIDs, ',', ''',''');

  SET @Query = CONCAT('UPDATE certificate SET CertificateStatus = 2, SignedDate = NOW() WHERE CertificateID IN (''', @v_CertificateIDs, ''');');

  PREPARE deleteQueryStatement FROM @Query;
  EXECUTE deleteQueryStatement;
END
$$

--
-- Create procedure `Proc_Certificate_SendMultiple`
--
CREATE DEFINER = 'admin'@'%'
PROCEDURE Proc_Certificate_SendMultiple (IN v_CertificateIDs text)
BEGIN
  SET @v_CertificateIDs = REPLACE(v_CertificateIDs, ',', ''',''');

  SET @Query = CONCAT('UPDATE certificate SET certificateStatus = 3, SentDate = NOW() WHERE CertificateID IN (''', @v_CertificateIDs, ''');');

  PREPARE deleteQueryStatement FROM @Query;
  EXECUTE deleteQueryStatement;
END
$$

--
-- Create procedure `proc_certificate_DeleteMultiple`
--
CREATE DEFINER = 'admin'@'%'
PROCEDURE proc_certificate_DeleteMultiple (IN v_CertificateIDs text)
BEGIN
  SET @v_CertificateIDs = REPLACE(v_CertificateIDs, ',', ''',''');

  SET @Query = CONCAT('UPDATE certificate SET isDeleted = 1 WHERE CertificateID IN (''', @v_CertificateIDs, ''');');

  PREPARE deleteQueryStatement FROM @Query;
  EXECUTE deleteQueryStatement;
END
$$

--
-- Create procedure `proc_certificate_BanMultiple`
--
CREATE DEFINER = 'admin'@'%'
PROCEDURE proc_certificate_BanMultiple (IN v_CertificateIDs text)
BEGIN
  SET @v_CertificateIDs = REPLACE(v_CertificateIDs, ',', ''',''');

  SET @Query = CONCAT('UPDATE certificate SET certificatestatus = 4 WHERE CertificateID IN (''', @v_CertificateIDs, ''');');

  PREPARE deleteQueryStatement FROM @Query;
  EXECUTE deleteQueryStatement;

  DEALLOCATE PREPARE deleteQueryStatement;
END
$$

DELIMITER ;

-- 
-- Dumping data for table user
--
INSERT INTO user VALUES
('stake_test1upgyluuflvwk2kdjxlfzxgqrly3r72652aaa3sj0hdeqdyceq4f0h', 100001, 'Vu Truong Giang', 'https://res.cloudinary.com/dog4lwypp/image/upload/v1679064292/Logo/35999755-2230-4f91-a405-df5bec1c11f6.jpg', '2023-05-26 10:35:18', 0, 0),
('stake_test1upvadt5zw4t5uw8tzzwl0xp5kaks0svzqg6hsfekhjl0fzs7k42ll', 100002, 'Tran Lam Lien', 'https://res.cloudinary.com/dog4lwypp/image/upload/v1679064292/Logo/35999755-2230-4f91-a405-df5bec1c11f6.jpg', '2023-05-26 10:35:18', 0, 0),
('stake_test1upzlwwvcu2cfajnzdcvthqw7snp2w2vsp4yceqsph8rx8cqna2ker', 100003, 'Le Dinh Minh', 'https://res.cloudinary.com/dog4lwypp/image/upload/v1679064292/Logo/35999755-2230-4f91-a405-df5bec1c11f6.jpg', '2023-05-26 10:35:19', 0, 0),
('stake_test1uqmw4ydawakkjwasf94w5f5frcrkt3t56taafgydh2wdkwqw3nks3', 100004, 'Bach 2', 'https://res.cloudinary.com/dog4lwypp/image/upload/v1679064292/Logo/35999755-2230-4f91-a405-df5bec1c11f6.jpg', '2023-05-26 10:35:19', 0, 0),
('stake_test1uqmw4ydawakkjwasf94w5f5frcrkt3t56taafgydh2wdkwqw3nksu', 100005, 'Trinh Xuan Bach', 'https://res.cloudinary.com/dog4lwypp/image/upload/v1679064292/Logo/35999755-2230-4f91-a405-df5bec1c11f6.jpg', '2023-05-26 10:35:20', 0, 0),
('stake_test1uqxvy9ntkxa9qe8t6f0phv4casn200w9zt4mcafutzu6jecgymvrs', 100006, 'Hiep Tran', 'https://res.cloudinary.com/dog4lwypp/image/upload/v1684684460/Logo/cedc80c2-ce96-4648-a416-d79ab5cf5db9.jpg', '2023-05-26 10:35:20', 0, 0),
('stake_test1uruq088hsj2jxxwgjhex6hkpfd2ap7jurhjnqhvfs8why2s0w4ltl', 100007, 'Tran Huy Hiep', 'https://res.cloudinary.com/dog4lwypp/image/upload/v1679064292/Logo/35999755-2230-4f91-a405-df5bec1c11f6.jpg', '2023-05-26 10:35:21', 0, 0),
('stake_test1urxp3zmykdlgh8vyldgkj5ltfwmvgw42l4g7m2ymc4a7hhg5rwegj', 100008, 'Dinh Minh', 'https://res.cloudinary.com/dog4lwypp/image/upload/v1684686005/Logo/92139c88-f073-4ed2-af00-dc504e1d3a6d.jpg', '2023-05-26 10:35:21', 0, 0),
('stake_test1uzjjsk25c6xc2ax57pvsvwdsncmta0nksfyvwdyq2ewlndqh9alfc', 100000, 'University of Transport and Communications', 'https://res.cloudinary.com/dog4lwypp/image/upload/v1679067306/Logo/f513d3d1-faa5-404d-a3ae-08221608e764.jpg', '2023-05-26 10:35:11', 0, 0);

-- 
-- Dumping data for table contact
--
-- Table sql12613779.contact does not contain any data (it is empty)

-- 
-- Dumping data for table certificate
--
-- Table sql12613779.certificate does not contain any data (it is empty)

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;